import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { XCircle, AlertCircle, Check, Star } from "lucide-react";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel";
import { Card, CardContent } from "@/components/ui/card";
import { About } from "@/components/About";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { AnimatedSection } from "@/components/AnimatedSection";

export default function Jahresrechnung() {
  return (
    <div className="min-h-screen bg-background text-foreground font-sans">
      <Header />
      <main>
        <section className="pt-32 pb-16 md:pt-40 md:pb-24 overflow-hidden bg-background">
          <div className="container px-4 mx-auto max-w-7xl"><div className="flex flex-col items-center text-center max-w-4xl mx-auto z-10"><AnimatedSection delay={100} className="w-full flex justify-center"><div className="inline-flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-2 rounded-full bg-secondary text-secondary-foreground text-[11px] sm:text-sm font-semibold mb-8 whitespace-nowrap"><div className="w-2 h-2 sm:w-2.5 sm:h-2.5 rounded-full bg-primary shrink-0" />Bereits 2.000+ zufriedene Nutzer in ganz Deutschland</div></AnimatedSection><AnimatedSection delay={200}><h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight text-foreground mb-6 leading-[1.1]">Stimmt deine Strom- oder Gasabrechnung wirklich?</h1></AnimatedSection><AnimatedSection delay={300}><p className="text-lg md:text-xl text-muted-foreground mb-10 max-w-2xl mx-auto leading-relaxed">Finde heraus, ob deine Jahresrechnung wirklich korrekt ist. Wir analysieren deine Abrechnung im Detail und zeigen dir transparent, ob alles stimmt.</p></AnimatedSection><AnimatedSection delay={400} className="w-full flex justify-center"><div className="flex flex-col items-center gap-4"><Button size="lg" className="w-full sm:w-auto text-lg h-16 px-10 rounded-xl bg-primary hover:bg-primary/90 text-primary-foreground font-bold shadow-lg shadow-primary/20 transition-all hover:scale-[1.02]">Jahresrechnung prüfen</Button><span className="text-sm text-muted-foreground">100% kostenlos</span></div></AnimatedSection></div></div>
        </section>
        <section className="bg-muted/30 py-20"><div className="container mx-auto px-4 text-center"><AnimatedSection><h2 className="text-3xl md:text-4xl font-bold mb-16">So funktioniert's</h2></AnimatedSection><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 max-w-6xl mx-auto text-left mb-16">{[{step:"1",title:"Rechnungsprüfung starten",desc:"Klicke dich durch ein paar kurze Fragen zu deinem Haushalt und lade deine Jahresrechnung hoch."},{step:"2",title:"Individuelle Analyse",desc:"Wir analysieren deine Jahresrechnung im Detail und prüfen, ob Auffälligkeiten, Fehler oder unnötige Kosten enthalten sind."},{step:"3",title:"Ergebnis erhalten",desc:"Du erhältst eine klare und verständliche Auswertung deiner Jahresrechnung – inklusive möglicher Auffälligkeiten und Einsparpotenziale."},{step:"4",title:"Konkrete Handlungsempfehlung",desc:"Auf Basis der Analyse zeigen wir, welche nächsten Schritte sinnvoll sind – z. B. Abschläge anpassen, Fehler korrigieren oder Einsparmöglichkeiten nutzen."}].map((item,i)=><AnimatedSection key={i} delay={i*100} className="h-full"><div className="flex flex-col items-start p-6 bg-card rounded-2xl shadow-sm border border-border/50 h-full"><div className="w-12 h-12 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xl font-bold mb-6 shadow-md">{item.step}</div><h3 className="text-xl font-bold mb-3">{item.title}</h3><p className="text-muted-foreground leading-relaxed">{item.desc}</p></div></AnimatedSection>)}</div><AnimatedSection delay={400}><Button size="lg" className="text-lg px-8 py-6 shadow-lg">Jahresrechnung prüfen</Button></AnimatedSection></div></section>
        <section className="py-20"><div className="container mx-auto px-4 text-center"><AnimatedSection><h2 className="text-3xl md:text-4xl font-bold mb-6 max-w-2xl mx-auto">Warum du deine Strom- oder Gasabrechnung prüfen solltest</h2><p className="text-lg text-muted-foreground max-w-3xl mx-auto mb-16">Viele Haushalte zahlen unnötig nach oder haben falsche Abschläge oft nur, weil kleine Fehler oder Änderungen in der Rechnung unbemerkt bleiben.</p></AnimatedSection><div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-5xl mx-auto mb-16 text-left">{[{title:"Geschätzte Zählerstände",desc:"Wenn kein aktueller Zählerstand gemeldet wird, schätzt der Anbieter den Verbrauch. Diese Schätzungen können deutlich vom tatsächlichen Verbrauch abweichen."},{title:"Abschläge wurden falsch berechnet",desc:"Manchmal sind monatliche Abschläge zu niedrig oder zu hoch angesetzt das fällt vielen erst mit der Jahresrechnung auf."},{title:"Tarifpreise haben sich geändert",desc:"Viele Tarife werden nach Ablauf der Preisgarantie oder durch Preisänderungen deutlich teurer. Ohne genaue Prüfung bleibt das oft unbemerkt."},{title:"Rechnungen sind schwer verständlich",desc:"Strom- und Gasrechnungen enthalten viele Positionen und Abkürzungen - dadurch ist es für viele Haushalte schwer zu erkennen, ob alles korrekt ist."}].map((item,i)=><AnimatedSection key={i} delay={i*100} className="h-full"><div className="bg-card p-8 rounded-2xl border shadow-sm hover:shadow-md transition-shadow h-full"><div className="w-10 h-10 rounded-full bg-primary/10 text-primary flex items-center justify-center mb-4"><AlertCircle className="w-5 h-5" /></div><h3 className="text-xl font-bold mb-3">{item.title}</h3><p className="text-muted-foreground">{item.desc}</p></div></AnimatedSection>)}</div></div></section>
        <section className="bg-primary text-primary-foreground py-12 md:py-20 px-4 text-center"><div className="container mx-auto max-w-4xl"><AnimatedSection><h2 className="text-2xl md:text-4xl font-bold mb-4 md:mb-6">Du musst deine Jahresrechnung nicht selbst verstehen oder analysieren.</h2><p className="text-base md:text-xl opacity-90 mb-6 md:mb-10 max-w-2xl mx-auto">Wir übernehmen das für dich und zeigen dir, ob deine Jahresrechnung wirklich korrekt ist.</p><div className="flex flex-col items-center"><Button size="lg" variant="secondary" className="text-base md:text-lg px-6 md:px-8 py-4 md:py-6 text-primary hover:text-primary font-bold shadow-lg">Jahresrechnung prüfen</Button><span className="text-xs opacity-80 mt-2 italic">100% kostenlos</span></div></AnimatedSection></div></section>
        <section className="py-24"><div className="container mx-auto px-4 text-center"><AnimatedSection><h2 className="text-3xl md:text-4xl font-bold mb-16">Rechnung selbst prüfen -<br className="hidden md:block" /> oder prüfen lassen</h2></AnimatedSection><div className="grid md:grid-cols-2 gap-8 max-w-5xl mx-auto mb-16"><AnimatedSection animation="fade-right" className="h-full"><div className="bg-muted/50 rounded-3xl p-8 md:p-12 text-left border h-full"><h3 className="text-2xl font-bold mb-8 text-center">Rechnung selbst prüfen</h3><ul className="space-y-6">{["Du musst alle Positionen und Abkürzungen in deiner Rechnung selbst verstehen.","Du musst prüfen, ob Verbrauch, Preise und Abschläge korrekt berechnet wurden.","Du musst mögliche Schätzungen oder ungewöhnliche Kosten selbst erkennen.","Du musst selbst beurteilen, ob deine Rechnung wirklich korrekt ist.","Du musst Zeit investieren, um die gesamte Rechnung im Detail zu analysieren."].map((text,i)=><li key={i} className="flex items-start gap-4"><XCircle className="w-6 h-6 text-muted-foreground shrink-0 mt-0.5" /><span className="text-muted-foreground leading-relaxed">{text}</span></li>)}</ul></div></AnimatedSection><AnimatedSection animation="fade-left" delay={200} className="h-full"><div className="bg-primary text-primary-foreground rounded-3xl p-8 md:p-12 text-left shadow-xl relative overflow-hidden h-full"><div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3"></div><h3 className="text-2xl font-bold mb-8 text-center relative z-10">Mit Energieassistent</h3><ul className="space-y-6 relative z-10">{["Professionelle Prüfung durch uns","Wir analysieren deine Jahresrechnung im Detail und prüfen alle relevanten Positionen.","Du erhältst eine klare und verständliche Auswertung deiner Rechnung.","Wir zeigen konkrete Handlungsempfehlungen für die nächsten Schritte.","Du erhältst ein verlässliches Ergebnis – ohne selbst Zeit investieren zu müssen."].map((text,i)=><li key={i} className="flex items-start gap-4"><div className="w-6 h-6 rounded-full bg-white/20 flex items-center justify-center shrink-0 mt-0.5"><Check className="w-4 h-4 text-white" /></div><span className="opacity-90 leading-relaxed">{text}</span></li>)}</ul></div></AnimatedSection></div><AnimatedSection delay={400}><Button size="lg" className="text-lg px-8 py-6 shadow-lg">Jahresrechnung prüfen</Button></AnimatedSection></div></section>
        <section className="bg-muted/30 py-24"><div className="container mx-auto px-4 text-center"><AnimatedSection><p className="text-primary font-semibold mb-2">Das sagen unsere Nutzer</p><h2 className="text-3xl md:text-4xl font-bold mb-16 max-w-3xl mx-auto">Über 2.000 Haushalte nutzen bereits den digitalen Energieassistenten</h2></AnimatedSection><AnimatedSection delay={200}><div className="max-w-5xl mx-auto px-4 md:px-12 relative mb-16"><Carousel opts={{ align: "start" }} className="w-full"><CarouselContent>{[{name:"Lisa K.",title:"Ich hatte erst eine Nachzahlung...",text:"Ich hatte erst eine Nachzahlung von über 1420 €. Durch die Prüfung habe ich gesehen, dass mein Zählerstand geschätzt wurde. Nachdem ich das korrigiert habe, waren es am Ende nur noch 680 €. Hat sich also wirklich gelohnt."},{name:"Tom S.",title:"Bei meiner Rechnung war zwar...",text:"Bei meiner Rechnung war zwar alles korrekt, aber ich habe trotzdem Hinweise bekommen, wie ich meinen Abschlag besser einstellen kann. Das fand ich wirklich sinnvoll."},{name:"Manny O.",title:"Ich habe meine Gasrechnung nie...",text:"Ich habe meine Gasrechnung nie richtig verstanden. Die Auswertung hier war viel einfacher zu lesen als die eigentliche Rechnung."},{name:"Hendrik M.",title:"Rechnung hochgeladen und nach...",text:"Rechnung hochgeladen und nach kurzer Zeit eine Auswertung bekommen. Fand ich wirklich praktisch, weil ich sonst gar nicht wüsste, worauf man achten muss."}].map((review,i)=><CarouselItem key={i} className="basis-[85%] md:basis-1/2 lg:basis-1/2 pl-4"><div className="p-1 h-full"><Card className="h-full border shadow-sm bg-card rounded-2xl"><CardContent className="flex flex-col h-full p-8 text-left"><div className="flex gap-1 text-[#16a34a] mb-4">{[1,2,3,4,5].map((star)=><Star key={star} className="w-5 h-5 fill-current border-none" />)}</div><h4 className="text-xl font-bold mb-3">{review.title}</h4><p className="text-muted-foreground leading-relaxed mb-4">{review.text}</p><p className="font-semibold text-foreground">{review.name}</p></CardContent></Card></div></CarouselItem>)}</CarouselContent><CarouselPrevious className="hidden md:flex -left-12 h-12 w-12 border shadow-md bg-background" /><CarouselNext className="hidden md:flex -right-12 h-12 w-12 border shadow-md bg-background" /></Carousel></div></AnimatedSection><AnimatedSection delay={400}><Button size="lg" className="text-lg px-8 py-6 shadow-lg">Jahresrechnung prüfen</Button></AnimatedSection></div></section>
        <About />
        <section className="py-12 border-y"><div className="container mx-auto px-4"><div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center max-w-5xl mx-auto"><AnimatedSection delay={100}><div className="space-y-2"><h3 className="text-4xl md:text-5xl font-bold text-primary">15.000+</h3><p className="text-muted-foreground font-medium">Tarife und Rechnungen<br />bereits geprüft</p></div></AnimatedSection><AnimatedSection delay={200}><div className="space-y-2 md:border-x border-border/50 h-full flex flex-col justify-center"><h3 className="text-4xl md:text-5xl font-bold text-primary">2.000+</h3><p className="text-muted-foreground font-medium">Haushalte nutzen den<br />Energieassistenten</p></div></AnimatedSection><AnimatedSection delay={300}><div className="space-y-2"><h3 className="text-4xl md:text-5xl font-bold text-primary">900.000+ €</h3><p className="text-muted-foreground font-medium">an Energiekosten bereits<br />eingespart</p></div></AnimatedSection></div></div></section>
        <section className="py-24"><div className="container mx-auto px-4 max-w-3xl"><AnimatedSection><h2 className="text-3xl md:text-4xl font-bold mb-12 text-center">Häufig gestellte Fragen</h2></AnimatedSection><AnimatedSection delay={200}><Accordion type="single" collapsible className="w-full space-y-4">{[{q:"Wie funktioniert die Prüfung meiner Jahresrechnung?",a:"Du klickst dich durch ein paar kurze Fragen und lädst deine Rechnung hoch. Wir analysieren deine Daten und zeigen dir an, ob es Auffälligkeiten gibt."},{q:"Sind meine Daten bei der Prüfung sicher?",a:"Ja, der Schutz deiner Daten hat höchste Priorität. Alle übermittelten Daten werden verschlüsselt übertragen und streng vertraulich behandelt. Nach der Prüfung werden deine Dokumente sicher gelöscht."},{q:"Kostet die Prüfung meiner Jahresrechnung etwas?",a:"Nein, die Prüfung deiner Jahresrechnung durch den Energieassistenten ist für dich zu 100% kostenlos und unverbindlich."},{q:"Wie finanziert sich der Energieassistent?",a:"Wir finanzieren uns ausschließlich über eine Provision der Energieversorger, falls du dich entscheidest, über uns in einen günstigeren Tarif zu wechseln. Für dich entstehen dabei keine zusätzlichen Kosten."},{q:"Was passiert, wenn Auffälligkeiten erkannt werden?",a:"Wenn wir Unstimmigkeiten in deiner Rechnung finden, erhältst du von uns konkrete Handlungsempfehlungen. Wir zeigen dir genau, welche Schritte du einleiten kannst, um dein Geld zurückzufordern oder zukünftige Abschläge anzupassen."},{q:"An wen kann ich mich wenden, wenn ich Fragen habe?",a:"Unser Kundenservice steht dir jederzeit zur Verfügung. Du kannst uns ganz einfach per E-Mail oder über unser Kontaktformular erreichen."}].map((faq,i)=><AccordionItem key={i} value={`item-${i}`} className="bg-muted/30 border px-6 rounded-lg"><AccordionTrigger className="text-left font-medium text-lg py-6 hover:no-underline hover:text-primary transition-colors">{faq.q}</AccordionTrigger><AccordionContent className="text-muted-foreground leading-relaxed pb-6">{faq.a}</AccordionContent></AccordionItem>)}</Accordion></AnimatedSection></div></section>
        <section className="bg-primary text-primary-foreground py-12 md:py-20 px-4 text-center"><div className="container mx-auto max-w-3xl"><AnimatedSection><h2 className="text-2xl md:text-4xl font-bold mb-4 md:mb-6">Unsicher, ob deine Jahresrechnung wirklich stimmt?</h2><p className="text-base md:text-xl opacity-90 mb-6 md:mb-10">Der Energieassistent analysiert deine Rechnung automatisch und zeigt dir sofort, ob alles korrekt ist oder ob du etwas prüfen solltest.</p><Button size="lg" variant="secondary" className="text-base md:text-lg px-6 md:px-8 py-4 md:py-6 text-primary hover:text-primary font-bold shadow-lg">Jahresrechnung prüfen</Button></AnimatedSection></div></section>
      </main>
      <Footer />
    </div>
  );
}
