import * as React from "react";
import * as ToastPrimitives from "@radix-ui/react-toast";
import { cva, type VariantProps } from "class-variance-authority";
import { X } from "lucide-react";
import { cn } from "@/lib/utils";
const ToastProvider = ToastPrimitives.Provider;
const ToastViewport = React.forwardRef<any,any>(({ className, ...props }, ref) => <ToastPrimitives.Viewport ref={ref} className={cn("fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4 sm:bottom-0 sm:right-0 sm:top-auto sm:flex-col md:max-w-[420px]", className)} {...props} />);
const toastVariants=cva("group pointer-events-auto relative flex w-full items-center justify-between space-x-4 overflow-hidden rounded-md border p-6 pr-8 shadow-lg",{variants:{variant:{default:"border bg-background text-foreground",destructive:"destructive group border-destructive bg-destructive text-destructive-foreground"}},defaultVariants:{variant:"default"}});
const Toast=React.forwardRef<any,any>(({className,variant,...props},ref)=><ToastPrimitives.Root ref={ref} className={cn(toastVariants({variant}),className)} {...props} />);
const ToastAction=React.forwardRef<any,any>(({className,...props},ref)=><ToastPrimitives.Action ref={ref} className={cn("inline-flex h-8 shrink-0 items-center justify-center rounded-md border bg-transparent px-3 text-sm font-medium",className)} {...props}/>);
const ToastClose=React.forwardRef<any,any>(({className,...props},ref)=><ToastPrimitives.Close ref={ref} className={cn("absolute right-2 top-2 rounded-md p-1",className)} toast-close="" {...props}><X className="h-4 w-4" /></ToastPrimitives.Close>);
const ToastTitle=React.forwardRef<any,any>(({className,...props},ref)=><ToastPrimitives.Title ref={ref} className={cn("text-sm font-semibold",className)} {...props}/>);
const ToastDescription=React.forwardRef<any,any>(({className,...props},ref)=><ToastPrimitives.Description ref={ref} className={cn("text-sm opacity-90",className)} {...props}/>);
type ToastProps=React.ComponentPropsWithoutRef<typeof Toast>; type ToastActionElement=React.ReactElement<typeof ToastAction>;
export { type ToastProps, type ToastActionElement, ToastProvider, ToastViewport, Toast, ToastTitle, ToastDescription, ToastClose, ToastAction };
